import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: NextRequest) {
  try {
    const { email, topic, score, total, details, difficulty } = await req.json();

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS },
      tls: { rejectUnauthorized: false },
    });

    const pct = Math.round((score / total) * 100);
    const emoji = pct >= 80 ? '🏆' : pct >= 60 ? '👍' : '📚';
    const detailsHtml = details.map((d: any, i: number) => `
      <div style="padding:12px;border-radius:10px;margin-bottom:10px;background:${d.ok ? '#f0fdf4' : '#fef2f2'};border:1px solid ${d.ok ? '#bbf7d0' : '#fecaca'}">
        <p style="font-weight:600;margin:0 0 4px;color:#1a1d2e">${i + 1}. ${d.q}</p>
        <p style="margin:0;font-size:13px;color:${d.ok ? '#16a34a' : '#dc2626'}">${d.chosen} ${d.ok ? '✓' : '✗'}</p>
        ${!d.ok ? `<p style="margin:4px 0 0;font-size:13px;color:#16a34a">✅ Correct: ${d.correct}</p>` : ''}
        ${!d.ok && d.explanation ? `<p style="margin:8px 0 0;font-size:12px;color:#4b5563;padding:8px;background:#f0f9ff;border-radius:6px;border-left:3px solid #3b82f6">💡 ${d.explanation}</p>` : ''}
      </div>
    `).join('');

    await transporter.sendMail({
      from: `"EduAI Portal" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: `${emoji} Quiz Report: ${topic} — ${score}/${total}`,
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:auto;padding:30px;background:#f8faff;border-radius:16px">
          <h2 style="color:#3b82f6">🎓 EduAI Portal — Quiz Report</h2>
          <div style="background:#1e293b;border-radius:12px;padding:20px;text-align:center;margin:16px 0;color:#fff">
            <div style="font-size:48px">${emoji}</div>
            <h3 style="margin:8px 0 4px;font-size:20px">${topic}</h3>
            <p style="color:#94a3b8;margin:0;text-transform:capitalize">Difficulty: ${difficulty}</p>
            <div style="font-size:32px;font-weight:800;color:#60a5fa;margin-top:10px">${score}/${total} — ${pct}%</div>
          </div>
          <h3 style="color:#374151;margin:20px 0 12px">Question Breakdown</h3>
          ${detailsHtml}
          <p style="color:#6b7280;font-size:12px;margin-top:20px">Generated by EduAI Portal · Keep learning! 🚀</p>
        </div>
      `,
    });

    return NextResponse.json({ ok: true });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
