import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: NextRequest) {
  try {
    const { email, stats, total, correct, pct } = await req.json();

    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS },
      tls: { rejectUnauthorized: false },
    });

    const emoji = pct >= 70 ? '🏆' : pct >= 40 ? '📈' : '📚';
    const topicsHtml = stats.filter((s: any) => s.asked > 0).map((s: any) => {
      const p = Math.round((s.correct / s.asked) * 100);
      const isWeak = p < 60;
      return `
        <div style="display:flex;justify-content:space-between;align-items:center;padding:8px 12px;border-radius:8px;margin-bottom:6px;background:${isWeak ? '#fef2f2' : '#f0fdf4'};border:1px solid ${isWeak ? '#fecaca' : '#bbf7d0'}">
          <span style="font-size:13px;color:#374151;font-weight:500">${s.topic.slice(0, 40)}${s.topic.length > 40 ? '...' : ''}</span>
          <span style="font-size:13px;font-weight:700;color:${isWeak ? '#dc2626' : '#16a34a'}">${p}% ${isWeak ? '⚠' : '✓'}</span>
        </div>
      `;
    }).join('');

    await transporter.sendMail({
      from: `"EduAI Portal" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: `${emoji} Your EduAI Progress Report — ${pct}% Overall`,
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:auto;padding:30px;background:#f8faff;border-radius:16px">
          <h2 style="color:#3b82f6">🎓 EduAI Portal — Progress Report</h2>
          <div style="background:#1e293b;border-radius:12px;padding:24px;text-align:center;margin:16px 0;color:#fff">
            <div style="font-size:48px">${emoji}</div>
            <div style="font-size:36px;font-weight:800;color:#60a5fa;margin:10px 0">${pct}%</div>
            <p style="color:#94a3b8;margin:0">Overall Score</p>
            <div style="display:flex;justify-content:center;gap:20px;margin-top:16px">
              <div><div style="font-size:20px;font-weight:700">${total}</div><div style="font-size:11px;color:#94a3b8">Questions</div></div>
              <div><div style="font-size:20px;font-weight:700">${correct}</div><div style="font-size:11px;color:#94a3b8">Correct</div></div>
              <div><div style="font-size:20px;font-weight:700">${stats.filter((s: any) => s.asked > 0).length}</div><div style="font-size:11px;color:#94a3b8">Topics</div></div>
            </div>
          </div>
          ${topicsHtml ? `<h3 style="color:#374151;margin:20px 0 12px">Topics Breakdown</h3>${topicsHtml}` : ''}
          <p style="color:#6b7280;font-size:12px;margin-top:20px">Generated by EduAI Portal · Keep learning! 🚀</p>
        </div>
      `,
    });

    return NextResponse.json({ ok: true });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
